title: "X157 Dev Notes"
description: One simulant attempts to share insight with others.
url: "https://x157.github.io"
theme: jekyll-theme-hacker
markdown: kramdown
timezone: "America/Los_Angeles"
lang: "en-US"
highlighter: rouge
defaults:
  -
    scope:
      path: "" # empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .idea
  - Dockerfile
  - docker-compose.yml
  - .dockerignore
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
kramdown:
  syntax_highlighter_opts:
    disable : true

google_cse_id: "d1a76fbc057564545"
